### ISSUE TITLE
Automated DeadMaster recovery in GTID mode

### ISSUE THREAD

**Issue by enisoc** [outbrain/orchestrator#121]
I'm experimenting with automated DeadMaster recovery with the following scenario:

1. Bring up 3 MariaDB (10.0.14) instances.
1. Manually set up GTID-based replication with 2 slaves replicating from the same master.
1. Configure and start Orchestrator, adding MariaDB instances through Discover page.
   * `ApplyMySQLPromotionAfterMasterFailover: true`
   * `RecoverMasterClusterFilters: ".*"`
1. Wait for Orchestrator to crawl the topology.
1. Terminate the master.

The automated recovery then kicks in and makes one of the remaining slaves the master of the other one, and sets the new master read-write. However, there were some side-effects that I didn't expect:

* The new master is still seen by Orchestrator as a slave, and it's marked red with "Problem: not replicating".
  * I expected that it would be marked as a healthy master.
* Replication was set up in non-GTID mode.
  * I expected it would maintain GTID mode since it was set that way originally.
  * Is there a setting to force all automated steps to use GTID mode?
* Unless I manually acknowledge the recovery, it seems like no subsequent automated recovery will ever be attempted.
  * It says "blocked due to a previous recovery".
  * I expected that it would allow itself to do another automated recovery after the anti-flapping period.

Then I start the old master back up (in read-only mode).

* Orchestrator still sees it as master, and the new master tries to reconnect to the old one to replicate.
  * I expected the new master would stay master, and the old one would automatically be told to replicate from the new master.

Is my expected behavior in these cases a supported flow right now with the right configuration?

**Comment by shlomi-noach** [comment]
As I noted, orchestrator is not instructed to actually detach the promoted slave. Today I pushed this configuration variable:
"ApplyMySQLPromotionAfterMasterFailover" (bool, default: false)
when 'true', orchestrator will remove the read-only flag and detach-slave on the newly promoted master. Eventually what you want is a `RESET SLAVE ALL`, this will be added shortly.

Why doesn't orchestrator do this by itself?
Because there's other stuff that may or may not need to be done upon master promotion. Do you enable the event scheduler? Do you iterate all the events that are `SLAVESIDE_DISABLED` and enable them? Does orchestrator have grants for that?
In my current workplace there are already tools that take care of anything that has to do with master promotion, including change DNS records etc. And so orchestrator just invokes them and lets them do what they do.

However I will improve on the ApplyMySQLPromotionAfterMasterFailover variable nonetheless.

RE: "Replication was set up in non-GTID mode.": let me look into this, this should definitely not be the case; orchestrator should maintain the existing setup (keep use GTID or keep not using GTID). I would like to have the `SHOW SLAVE STATUS` output on your initial two slaves before crashing the master, please. I'm also assuming both these slaves were running with `log-slave-updates`.

"Unless I manually acknowledge the recovery, it seems like no subsequent automated recovery will ever be attempted" -- "ever" is such a long time. The default is 60m; this is configurable by `RecoveryPeriodBlockMinutes`. Did you wait for 60 minutes? If not, please reduce to "1" or "0" for that matter and re-test. This should work well. 
Otherwise, if you did have a shorter timeout, here's another possibility: do you have an orchestrator daemon running somewhere, or did you just issue command line orchestrator for the recovery action? reason is that the daemon is the one in charge for expiring stuff and performing routine polls and cleanups, and that includes the blocking period cleanup for long standing recoveries.

To run orchestrator daemon you will either issue "orchestrator http", or, if you don't like HTTP mode, issue "orchestrator -c continuous"

I can potentially create a "-c one-time-cleanup" command; but without a running daemon I expect this will not do all the right things.

"I expected the new master would stay master, and the old one would automatically be told to replicate from the new master."
- true for the first part (relates to the above discussion); false for the second part. The crashed master may have been more-up-to-date than the promoted slave, unless used with lossless semi-syn, which I don't expect that you use.
This means we have lost some transactions during recovery, and cannot expect the old master to agree to replicate from the newly promoted master; it is already drifted out of sync.

**Comment by enisoc** [comment]
#### Promotion

I actually was using `ApplyMySQLPromotionAfterMasterFailover: true` already. I did a re-pull this morning when I noticed it was added. I guess I need to wait for `RESET SLAVE ALL` as well.

I see why you kept the post-failover actions separate. In my case, we don't use events or anything that needs to be reconfigured on the MySQL side after a failover. The equivalent of updating DNS records for us is sending an RPC to Vitess to tell it about the mastership change. I was planning to add a hook for that, so I can do any extra post-failover steps there if you think it makes more sense than making it a general config option.

#### GTID mode

Yes, all 3 MariaDB are running with `log-slave-updates` enabled. Here is the `SHOW SLAVE STATUS` output from a slave after my initial setup (the other slave's output is the same except for the relay log file name):

```
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
                  Master_Host: 172.27.74.97
                  Master_User: vt_repl
                  Master_Port: 33100
                Connect_Retry: 10
              Master_Log_File: vt-0000000100-bin.000001
          Read_Master_Log_Pos: 1778
               Relay_Log_File: vt-0000000101-relay-bin.000002
                Relay_Log_Pos: 1618
        Relay_Master_Log_File: vt-0000000100-bin.000001
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
              Replicate_Do_DB: 
          Replicate_Ignore_DB: 
           Replicate_Do_Table: 
       Replicate_Ignore_Table: 
      Replicate_Wild_Do_Table: 
  Replicate_Wild_Ignore_Table: 
                   Last_Errno: 0
                   Last_Error: 
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 1778
              Relay_Log_Space: 1923
              Until_Condition: None
               Until_Log_File: 
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File: 
           Master_SSL_CA_Path: 
              Master_SSL_Cert: 
            Master_SSL_Cipher: 
               Master_SSL_Key: 
        Seconds_Behind_Master: 0
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error: 
               Last_SQL_Errno: 0
               Last_SQL_Error: 
  Replicate_Ignore_Server_Ids: 
             Master_Server_Id: 100
               Master_SSL_Crl: 
           Master_SSL_Crlpath: 
                   Using_Gtid: Slave_Pos
                  Gtid_IO_Pos: 0-100-6
```

#### Recovery period

Sorry, I should have checked the value of `RecoveryPeriodBlockMinutes` before complaining. :) I'm used to a similar setting in another tool which defaults to 10 *seconds*, so I didn't think to check if the default value for Orchestrator was longer than the amount of time that had passed.

I'm running Orchestrator in `http` mode throughout the test, and that's how I plan to use it down the road as well.

#### Reconnect old master to new master

We do use semi-sync, although we accept the risk of phantom reads because it's not the new lossless semi-sync in 5.7. In the case where the old master comes back with an extra transaction that was committed but never acked, it should refuse to replicate because we also use GTID strict mode. So in this particular setup, it should be reasonably safe to attempt to reconnect the old master.

**Comment by shlomi-noach** [comment]
I do like the number of zeros padded.

Re: GTID, would you mind also showing me the relevant row `from
database_instance where hostname='that_slave_you_showed_slave_status_for';`
?

Re: Recovery period: right; and my variable is an `int` and called `
RecoveryPeriodBlockMinutes`. Good start. I can override with another
variable measured by seconds.

Re: reconnect old master
Let me think about this one; as far as current implementation goes, the
recovery is complete once the new master is promoted and topology is
intact. The old master may come back to life hours later, and needs be
patched back as a slave.

A couple issues:

- Need to note that down sometime that upon revival it should turn slave
- How to set credentials? Basically orchestrator does not know the
credentials for replication. When using system tables, it can query the
mysql database to get that info -- if has privileges. If it does not have
privileges, or `master.info` file is used, orchestrator does not know how
to `CHANGE MASTER TO ... MASTER_USER='???', MASTER_PASSWORD='???'`
-

**Comment by shlomi-noach** [comment]
I do like the number of zeros padded.

Re: GTID, would you mind also showing me the relevant row `from
database_instance where hostname='that_slave_you_showed_slave_status_for';`
?

Re: Recovery period: right; and my variable is an `int` and called `
RecoveryPeriodBlockMinutes`. Good start. I can override with another
variable measured by seconds.

Re: reconnect old master
Let me think about this one; as far as current implementation goes, the
recovery is complete once the new master is promoted and topology is
intact. The old master may come back to life hours later, and needs be
patched back as a slave.

A couple issues:

- Need to note that down sometime that upon revival it should turn slave
- How to set credentials? Basically orchestrator does not know the
credentials for replication. When using system tables, it can query the
mysql database to get that info -- if has privileges. If it does not have
privileges, or `master.info` file is used, orchestrator does not know how
to `CHANGE MASTER TO ... MASTER_USER='???', MASTER_PASSWORD='???'`

**Comment by enisoc** [comment]
Here's the row you mentioned from `database_instance`:

```
*************************** 2. row ***************************
               hostname: my-workstation-fqdn
                   port: 33101
           last_checked: 2015-11-05 18:12:07
   last_attempted_check: 2015-11-05 18:12:07
              last_seen: 2015-11-05 18:12:07
                 uptime: 168
              server_id: 101
            server_uuid: 
                version: 10.0.14-MariaDB-1~trusty-log
          binlog_server: 0
              read_only: 1
          binlog_format: STATEMENT
                log_bin: 1
      log_slave_updates: 1
        binary_log_file: vt-0000000101-bin.000001
         binary_log_pos: 1284
            master_host: my-workstation-fqdn
            master_port: 33100
      slave_sql_running: 1
       slave_io_running: 1
has_replication_filters: 0
            oracle_gtid: 0
      executed_gtid_set: 
   supports_oracle_gtid: 0
           mariadb_gtid: 1
            pseudo_gtid: 0
        master_log_file: vt-0000000100-bin.000001
    read_master_log_pos: 1778
  relay_master_log_file: vt-0000000100-bin.000001
    exec_master_log_pos: 1778
         relay_log_file: vt-0000000101-relay-bin.000002
          relay_log_pos: 1618
         last_sql_error: 
          last_io_error: 
  seconds_behind_master: 0
      slave_lag_seconds: 0
              sql_delay: 0
        num_slave_hosts: 1
            slave_hosts: [{"Hostname":"my-workstation-fqdn","Port":33101}]
           cluster_name: my-workstation-fqdn:33100
suggested_cluster_alias: 
            data_center: 
   physical_environment: 
      replication_depth: 1
           is_co_master: 0
```
